[build]
builder = "NIXPACKS"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"

[[services]]
name = "auth-service"
dockerfile = "auth_service/Dockerfile"
port = 8000

[[services]]
name = "voice-service"
dockerfile = "voice_service/Dockerfile"
port = 8001 